codecov:
  notify:
    wait_for_ci: false
  require_ci_to_pass: true
  strict_yaml_branch: master
  branch: master

coverage:
  precision: 2
  round: down
  range: "70...100"

  status:
    src:
      target: auto
      threshold: 7%
      base: auto
      if_ci_failed: success
      paths:
        - src/
      flags:
        - src

    project:
      default:
        base: auto
        informational: true
        target: 95%
        threshold: 1%

    patch:
      default:
        informational: true
        target: 80%
        threshold: 1%
    changes: no

  notify:
    # Wait for reasonable amount of tests to complete before
    # reporting coverage
    after_n_builds: 8

  ignore:
    - "**/generated/**"
    - "data"
    - "docs"
    - "scripts"
    - "tests"

flags:
  src:
    paths:
      - src

parsers:
  gcov:
    branch_detection:
      conditional: yes
      loop: yes
      method: no
      macro: no

comment:
  layout: "header, reach, diff, flags, files, footer"
  behavior: default
  require_changes: false
  require_base: false
  require_head: true
  branches: [ "master" ]
