version = 1

test_patterns = ["*/tests/**"]

exclude_patterns = [
    "scripts/**,",
    "dist/**"
]

[[analyzers]]
name = "javascript"
enabled = true

  [analyzers.meta]
  dialect = "typescript"
  ecma_version = "2020"
  style_guide = "airbnb"
  environment = [
    "nodejs",
    "browser",
    "jest"
  ]
