#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

npm run all
npm run test:all
npm run changelog

git add api/
git add docs/
git add src/
git add tests/
git add typings/

git add README.md
git add CHANGELOG.md
git add package-lock.json
